// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRPAjs9LC-sv6UC-0qqj3wrYBoBW4jqtQ',
    appId: '1:595661721350:android:dcc0d869baf66624a35887',
    messagingSenderId: '595661721350',
    projectId: 'siade-2026',
    storageBucket: 'siade-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNU9tJG1Eyb55FM0YUlT-Xe5JFGViTYPk',
    appId: '1:595661721350:ios:aecddecfb77aacf6a35887',
    messagingSenderId: '595661721350',
    projectId: 'siade-2026',
    storageBucket: 'siade-2026.firebasestorage.app',
    androidClientId: '595661721350-2ues1p9bhhl0cj8lvcs268g3cgjjjg1l.apps.googleusercontent.com',
    iosClientId: '595661721350-9l7jvfd7av8uun313mfsq4o2jjek8ri9.apps.googleusercontent.com',
    iosBundleId: 'com.sahanalytics.siadeapp',
  );
}
